//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS_Lab3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RnBEntities : DbContext
    {
        public RnBEntities()
            : base("name=RnBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<marker> markers { get; set; }
    
        public virtual ObjectResult<string> GetRnB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetRnB");
        }
    
        public virtual ObjectResult<string> GetRnB1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetRnB1");
        }
    }
}
